# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-cloud-kwik'
    organization: '210503-reston-net'
    scannerMode: 'MSBuild'
    projectKey: '210503-Reston-NET_GACD-P2-UI'
    projectName: 'GACD-P2-UI'
    extraProperties: |
      sonar.sourceEncoding=UTF-8
      sonar.exclusions=**/mode_modules/**,**/*.spec.ts
      sonar.tests=src
      sonar.test.inclusions=**/*spec.ts
      sonar.typescript.lcov.reportPaths=${Build.SourcesDirectory)/**/coverage/lcov.info
      sonar.typescript.exclusions=**/node_modules/**,**/typings.d.ts,**/main.ts,**/environments/environment*.ts, **/*routing.module.ts

#Build
- script: |
    npm install -g @angular/cli
    cd Ang-GACD-UI
    npm install
    ng build --prod="true"
    zip -r dist/app.zip dist/Ang-GACD-UI
  displayName: 'npm install and build'

#Test

- script: |
    cd Ang-GACD-UI   
    export CHROME_BIN=$(which google-chrome)
    npx ng test --browsers ChromeHeadlessNoSandbox --watch=false --karmaConfig karma.conf.js --code-coverage
  
  displayName: "Running Tests"
  continueOnError: True
  
- script: |
     cd Ang-GACD-UI
     npm run sonar

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/Ang-GACD-UI/coverage/Ang-GACD-UI/cobertura.txt'

#Deploy
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'kwikcode-azure'
    appType: 'webAppLinux'
    WebAppName: 'kwikkoder'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|14-lts'
    StartupCommand: 'pm2 serve /home/site/wwwroot/dist/Ang-GACD-UI --no-daemon --spa'

