# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

#Build
- script: |
    npm install -g @angular/cli
    cd Ang-GACD-UI
    npm install
    ng build --prod="true"
    zip -r dist/app.zip dist/Ang-GACD-UI
  displayName: 'npm install and build'

#Test
- script: |
    cd Ang-GACD-UI
    which google-chrome
    export CHROME_BIN=$(which google-chrome)
    echo $CHROME_BIN
    npx ng test --browsers ChromeHeadless --watch=false --karmaConfig karma.conf.js --code-coverage

  displayName: "Running Tests"

#Deploy
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'kwikcode-azure'
    appType: 'webAppLinux'
    WebAppName: 'kwikkoder'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|14-lts'
    StartupCommand: 'pm2 serve /home/site/wwwroot/dist/Ang-GACD-UI --no-daemon --spa'

